[project]
name = "studymate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ItStress", email = "marconapolitano02@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "httpx>=0.28.1",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.6",
    "pypdf>=6.19.0",
]

[project.scripts]
studymate = "studymate:main"
studymate-migrate = "studymate.migrations:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.fastapi]
entrypoint = "studymate.main:app"
